fab: fab29
gateway: http://fz1.fab29-staging.com
namespace: name-b
app-deploy:
  appB:
    test: abc
  appC:
  - name: v604
    resource:
      cpu: 7
      gpu: 7
      hpa:
        dataa: 3
        datab: 3
  - name: v512
    resource:
      cpu: 8
      gpu: 6
      hpa:
        dataa: 3
        datab: 3
  appA:
    web: fab14-staging.com.tw/name-b
    images:
    - version: 2026.04.0
      id: 2565468
    - version: 2025.12.1
      id: 2565466
    FAB29:
      p1:
      - name: v604
        shadow: 5
        replict: 6
        resource:
          cpu: 10
          gpu: 10
          hpa:
            dataa: 6
            datab: 6
          res:
            dataa: 7
            datab: 7
      - name: v512
        shadow: 6
        replict: 5
        resource:
          cpu: 10
          gpu: 10
          res:
            dataa: 7
            datab: 7
      p2:
      - name: v604
        shadow: 6
        replict: 7
        resource:
          cpu: 11
          gpu: 11
          hpa:
            dataa: 7
            datab: 7
          res:
            dataa: 8
            datab: 8
      - name: v512
        shadow: 7
        replict: 6
        resource:
          cpu: 11
          gpu: 11
          res:
            dataa: 8
            datab: 8
      p3:
      - name: v604
        shadow: 2
        replict: 3
        resource:
          cpu: 7
          gpu: 7
          hpa:
            dataa: 3
            datab: 3
          res:
            dataa: 4
            datab: 4
      - name: v512
        shadow: 3
        replict: 2
        resource:
          cpu: 7
          gpu: 7
          res:
            dataa: 4
            datab: 4
  service-b-fab29:
    enabled: true
    resource:
      cpu: 4
      gpu: 1
      hpa:
        dataa: 12
        datab: 22
flow-deploy:
  appAA:
    config-v604: abc
    config-v512: abc
  appBB:
  - name: v412
    resource:
      cpu: 7
      gpu: 7
      hpa:
        dataa: 3
        datab: 3
  - name: v407
    resource:
      cpu: 8
      gpu: 6
      hpa:
        dataa: 3
        datab: 3
  appEE:
    resource:
      cpu: 7
      gpu: 7
      hpa:
        dataa: 3
        datab: 3
  appFA:
  - name: v412
    resource:
      cpu: 8
      gpu: 6
      hpa:
        dataa: 3
        datab: 3
  - name: v407
    resource:
      cpu: 8
      gpu: 6
      hpa:
        dataa: 3
        datab: 3
target: FAB29-FZ1
environment: staging
