"""Shared default values for the 24h runner contract."""
from __future__ import annotations

DEFAULT_BACKEND = "qwen"
DEFAULT_QWEN_COMMAND = "qwen.cmd"
DEFAULT_AGENT_TIMEOUT = 7200
DEFAULT_PLANNING_TIMEOUT = 600
DEFAULT_AGENT_IDLE_AFTER_CHANGE_TIMEOUT = 900
DEFAULT_VALIDATOR_TIMEOUT = 1200
DEFAULT_MAX_ATTEMPTS = 0
DEFAULT_MAX_CYCLES = 0

DEFAULT_TASK_FEEDBACK_LIMIT = 2000
DEFAULT_PLAN_PROGRESS_FEEDBACK_LIMIT = 8000
DEFAULT_PLAN_QUALITY_REPLANS = 1
DEFAULT_PLANNING_FAILURES_BEFORE_FALLBACK = 3

DEFAULT_PROCESS_OUTPUT_CHARS = 4 * 1024 * 1024
VALIDATOR_REPORT_DIR_ENV = "AI_TASK_RUNNER_REPORT_DIR"
