"""Bundled stage presets and workflow data. No flow-building code lives here."""

STAGES = {
    "plan": {
        "stage": "plan",
        "name": "planning",
        "status": "AI 正在產生任務規劃",
        "run_state": "planning",
        "mode": "readonly",
        "model_mode": "planning",
        "timeout_attr": "planning_timeout",
        "prompt_builder": "planning_prompt",
        "result_handler": "finish_plan",
        "plan_only_stop": True,
    },
    "repair_plan": {
        "stage": "plan",
        "status": "AI 正在建立修復規劃",
        "run_state": "planning",
        "mode": "readonly",
        "model_mode": "planning",
        "timeout_attr": "planning_timeout",
        "prompt_builder": "repair_plan_prompt",
        "result_handler": "finish_plan",
    },
    "execute": {
        "stage": "global",
        "status": "AI 正在處理目前任務",
        "run_state": "executing",
        "mode": "write",
        "actor": "executor",
        "track_changes": True,
        "prompt": "stages/execution.md",
        "result_handler": "finish_execute",
    },
    "repair": {
        "stage": "global",
        "status": "AI 正在修復目前任務",
        "run_state": "executing",
        "mode": "write",
        "actor": "executor",
        "track_changes": True,
        "prompt": "stages/execution.md",
        "result_handler": "finish_repair",
    },
    "review": {
        "stage": "global",
        "status": "AI 正在確認任務是否完成",
        "run_state": "reviewing",
        "mode": "readonly",
        "model_mode": "review",
        "fresh_model": True,
        "model_key": "review_model",
        "timeout_attr": "planning_timeout",
        "prompt_builder": "review_prompt",
        "parser": "parse_review",
        "result_status": "completed_status",
        "result_handler": "finish_review",
        "retry_attr": "review_retries",
        "skip_on_error": True,
    },
    "validate_file": {
        "stage": "python_validation",
        "status": "正在執行 File Validator",
        "run_state": "validating",
        "mode": "write",
        "actor": "validator",
        "result_handler": "finish_validation",
    },
    "validate_ai": {
        "stage": "global",
        "status": "正在執行最終 AI 驗證",
        "run_state": "validating",
        "mode": "readonly",
        "actor": "validator",
        "condition": "needs_ai_validation",
        "fresh_model": True,
        "fresh_each_review": True,
        "model_key": "ai_validation_model",
        "structured_retries": 2,
        "structured_fresh_retries": 1,
        "retry": 0,
        "reviews_attr": "final_ai_validations",
        "prompt": "stages/ai_validator.md",
        "parser": "parse_ai_validation_stage",
        "result_status": "validation_status",
        "result_handler": "finish_final_validation",
    },
}

# Workflow topology is intentionally visible in one place.
FLOWS = {
    "default": ["plan", "validate_file", "validate_ai"],
    "todo": ["execute", "review"],
    "repair": ["repair", "review"],
    "validators": ["validate_file", "validate_ai"],
    "replan": ["plan", "validate_file", "validate_ai"],
    "validator_repair": ["repair_plan", "validate_file", "validate_ai"],
}

DEFAULT_FLOW = FLOWS["default"]

__all__ = ["DEFAULT_FLOW", "FLOWS", "STAGES"]
